### ISSUE TITLE
Parents aren't distributed over comma-separated children

### ISSUE THREAD

**Issue by Nixinova** [Nixinova/NovaSheets#4]
```sass
#header {
   .child1, child2 {display:none;}
}
```
Compiles to 
```css
#header .child1, child2 {display:none;}
```
